## Get more comfortable with Arrays

In [2]:
import numpy as np

Solve 0s and 1s

In [15]:
# sort 0's and 1's 
arr = np.array([1,1,0,0,0,0,1,0,1], dtype=np.int32)
arr

array([1, 1, 0, 0, 0, 0, 1, 0, 1], dtype=int32)

In [16]:
i = 0
j = arr.size - 1
while (i < j):
    if arr[i] == 0:
        i += 1
    else:
        arr[i], arr[j] = arr[j], arr[i]
    
    if arr[j] == 1:
        j -= 1
    else:
        arr[i], arr[j] = arr[j], arr[i]

    print(arr)

print(arr)

[1 1 0 0 0 0 1 0 1]
[0 1 0 0 0 0 1 1 1]
[0 1 0 0 0 0 1 1 1]
[0 0 0 0 0 1 1 1 1]
[0 0 0 0 0 1 1 1 1]
[0 0 0 0 0 1 1 1 1]
[0 0 0 0 0 1 1 1 1]
[0 0 0 0 0 1 1 1 1]


Dutch National Flag

In [17]:
arr = np.array([2,2,0,1,1,0,0,1,2,0,2,2,1,1,0])

In [19]:
i, j, k = 0,arr.size - 1,0
while (i < j and k < j):
    if arr[i] == 0:
        i += 1
        if k < i:
            k += 1
    elif arr[k] == 0:
        arr[i], arr[k] = arr[k], arr[i]
        i += 1
        if k < i:
            k += 1
    elif arr[j] == 2:
        j -= 1
    elif arr[k] == 2:
        arr[j], arr[k] = arr[k], arr[j]
        j -= 1
    else:
        k += 1

print(arr)


[0 0 0 0 0 1 1 1 1 1 2 2 2 2 2]


In [21]:
n = [1,2,3]
len(n)

3

takes 2's compliment

In [47]:
arr = np.array([0,0,1,1,1,0,1])
print(arr)

for i in range(0,arr.size):
    if arr[i] == 0:
        arr[i] = 1
    else:
        arr[i] = 0
print(arr)


flag = 1

i = arr.size - 1
while (i >= 0):
    if  arr[i] + flag == 0:
        i -= 0
        flag = 0
        i -= 1
    elif arr[i] + flag == 1:
        arr[i] = 1
        flag = 0
        i -= 1
    elif arr[i] + flag == 2:
        arr[i] = 0 
        flag = 1
        i -= 1


print(flag)
if flag == 1:
    print(flag, arr)
else:
    print(arr)

[0 0 1 1 1 0 1]
[1 1 0 0 0 1 0]
0
[1 1 0 0 0 1 1]


In [90]:
num = 1
binary = []
while (num != 0):
    if num&1 == 0:
        binary.append(0)
    else:
        binary.append(1)

    num //= 2

binary = binary[::-1] 
binary

[1]

In [91]:
for i in range(0,len(binary)):
    if binary[i] == 0:
        binary[i] = 1
    else:
        binary[i] = 0

print(binary)

[0]


In [92]:
number = 0
size = len(binary) - 1
for i in range(len(binary) -1, -1, -1):
    number = number + binary[i]*pow(2,size - i)
    # print(number)
    print('elelment', pow(2,size-i), 'actual',binary[i], 'sum', number, 'power', size - i)
print(number)

elelment 1 actual 0 sum 0 power 0
0


In [102]:
nums = [3,2,4]
hash_map = {} # val: index
target = 7
for i, j in enumerate(nums):
    difference = target - j
    if difference in hash_map:
        print(hash_map[difference],i)
        pass
    else:
        hash_map[j] = i

0 2


In [23]:
arr = np.array([1,2,3,4,5], dtype=np.int32)
target = 7  

In [30]:
ans = {}

for i, j in enumerate(arr):
    diff = target - j
    if diff in ans:
        print(f'{j} at index {i} and {diff} at index {ans[diff]} gives {target}')
        break
    else:
        ans[j] = i

4 at index 3 and 3 at index 2 gives 7


In [ ]:
l = [10,20,30,40]

for i in range(0,len(l)):
    for j in range(i,len(l)):
        print(l[i],l[j])
    print('')

10 10
10 20
10 30
10 40

20 20
20 30
20 40

30 30
30 40

40 40



### Shifiting array to right

In [52]:
arr = np.array([1,2,3,4,5], dtype=np.int32)

def shifting_to_right(arr, pos: int):
    pos = pos % 5
    temp = np.zeros(10,dtype=np.int32)
    n = len(arr)
    # step one, store in temporary array all the elements that will come before as per pos
    for i in range(0,pos):
        temp[i] = arr[n - pos + i]
    
    # step 2
    for i in range(0,n-pos):
        arr[n - i - 1] = arr[n - pos - i - 1]

    # step 3, put the temp array in front
    for i in range(0,pos):
        arr[i] = temp[i]

    return arr

print(shifting_to_right(arr,4))


[2 3 4 5 1]
