In [1]:
import numpy as np

### Find pivot index: Leetcode (Already done two sum efficient solution using dictionary and quick search in dict)

In [23]:
z = np.array([1,7,3,6,5,6])

In [24]:
lsum = 0
rsum = 0
for i in range(1,len(z)):
    rsum += z[i]

print(rsum)

i = 0
while (i < len(z)-1):
    if rsum == lsum:
        print(i)
        break
    else:
        lsum += z[i]
        i += 1
        rsum -= z[i]
    print(rsum,lsum)
    if rsum == lsum:
        print(i)

27
20 1
17 8
11 11
3
3


### Find Pivot index two array storage method

In [35]:
z = np.array([1,1,-1,-1,0])
larr = np.zeros(z.size,dtype=np.int32)
rarr = np.zeros(z.size,dtype=np.int32)
temp = 0
for i in range(len(z)):
    larr[i] = temp
    temp += z[i]
temp = 0
for i in range(len(z)):
    rarr[len(z) - 1 - i] = temp
    temp += z[len(z) - 1 - i]

print(larr)
print(rarr)

for i in range(len(z)):
    if larr[i] == rarr[i]:
        print(i)
    



[0 1 2 1 0]
[-1 -2 -1  0  0]
4


### Removing duplicates and finding total no. of unique elements

In [41]:
arr = np.array([0,0,1,1,1,2,2,3,3,4],dtype=np.int32)

In [42]:
i, j = 0, 0
while (j < len(arr)):
    if arr[i] == arr[j]:
        j += 1
    else:
        i += 1
        arr[i] = arr[j]

print(arr, i)

[0 1 2 3 4 2 2 3 3 4] 4


### Moving average in window

In [49]:
arr = np.array([5],dtype=np.int32)
k = 1
initial_sum = 0
for i in range(0,k):
    initial_sum += arr[i]

# avg_ans = initial_sum / k
temp_sum = initial_sum
i = 1
while (i + k -1 < len(arr)):
    temp_sum += arr[i + k - 1]
    temp_sum -= arr[i - 1]
    initial_sum = max(initial_sum, temp_sum)
    i += 1

print( initial_sum / k )

5.0


### Return duplicate number

In [51]:
arr = np.array([1,3,4,2,2],dtype=np.int32)

temp_dict = {}

for i in range(0, len(arr)):
    if arr[i] in temp_dict:
        print(arr[i])
    else:
        temp_dict[arr[i]] = i



2


### Missing elements from an Array with Duplicates

In [ ]:
arr = np.array([1,3,5,3,4],dtype=np.int32)
temp = arr.copy()

for i in range(0,len(arr)):
    temp[arr[i] -1] = -1
    # print(temp, arr[i])

# print(temp)

ans = 0
for i in range(0, len(arr)):
    if temp[i] != -1:
        ans = i

print(ans + 1)



[-1  3 -1 -1 -1]
2


#### Find the first repeating element

In [70]:
from collections import Counter

In [71]:
arr = np.array([1,5,3,4,3,5,6],dtype=np.int32)

temp_dict = {}

count_map = Counter(arr)
count_map


Counter({np.int32(5): 2,
         np.int32(3): 2,
         np.int32(1): 1,
         np.int32(4): 1,
         np.int32(6): 1})

In [ ]:
for i, j in count_map.items():
    if j > 1:
        print(i) 
        break

5


### Common elements in 3 sorted arrays

In [2]:
arr1 = np.array([1,5,10,20,40,80])
arr2 = np.array([6,7,20,80,100])
arr3 = np.array([3,4,15,20,30, 70, 80, 120])

In [9]:
i, j, k = 0, 0, 0

n1, n2, n3 = len(arr1), len(arr2), len(arr3)

while (i < n1 and j < n2 and k < n3):
    if arr1[i] == arr2[j] and arr2[j] == arr3[k]:
        print(f'arr1 at {i}, arr2 at {j} and arr3 at {k} has common element {arr1[i]}')
        break
    # elif arr1[i] < arr2[j] and arr1[i] < arr3[k]:
    #     i += 1
    # elif arr2[j] < arr1[i] and arr2[j] < arr3[k]:
    #     j += 1
    # elif arr3[k] < arr2[j] and arr3[k] < arr1[i]:
    #     k += 1
    min_value = min(arr1[i], arr2[j], arr3[k])
    i += arr1[i] == min_value
    j += arr2[j] == min_value
    k += arr3[k] == min_value


"""
Ternary Operator
value_if_true if condition1 else value_if_false
value_if_true if conditon else value_if_false
value1 if condition1 else value2 if condition2 else value3 if condition3 else value4
"""

arr1 at 3, arr2 at 2 and arr3 at 3 has common element 20


'\nTernary Operator\nvalue_if_true if condition1 else value_if_false\nvalue_if_true if conditon else value_if_false\nvalue1 if condition1 else value2 if condition2 else value3 if condition3 else value4\n'

### Wave print a matrix

In [30]:
mat = np.arange(12,dtype=np.int32)
mat = mat.reshape(3,4)
print(mat)

for i in range(0,len(mat[0])):
    for j in range(0, len(mat)):
        if i&1 == 0:
            print(mat[j][i], end=' ')
        else:
            print(mat[len(mat) - j - 1][i], end=' ')


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
0 4 8 9 5 1 2 6 10 11 7 3 

### Sprial Print Matrix

In [71]:
mat = np.arange(12,dtype=np.int32)
mat = mat.reshape(3,4)
print(mat)


left_index, right_index, up_index, bottom_index = 0, len(mat[0]) - 1, 0, len(mat) - 1
# print(left_index, right_index, up_index, bottom_index)
print('='*50)

counter = len(mat) * len(mat[0])

while (counter > 0):
    # First we print first row
    for i in range(left_index,right_index + 1):
        print(mat[up_index][i], end=' ')
        counter -= 1 
    up_index += 1

    if counter == 0:
        break

    # Second we print right side column, but no duplicate
    for i in range(up_index, bottom_index + 1):
        print(mat[i][right_index], end=' ')
        counter -= 1
    right_index -= 1

    if counter == 0:
        break

    # Third we print bottom row
    for i in range(right_index, left_index -1, -1):
        print(mat[bottom_index][i], end=' ')
        counter -= 1
    bottom_index -= 1

    if counter == 0:
        break

    # Finally the first collumn from bottom up needs to be printed
    for i in range(bottom_index, up_index -1, -1):
        print(mat[i][left_index], end=' ')
        counter -= 1
    left_index += 1

    if counter == 0:
        break



    

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
0 1 2 3 7 11 10 9 8 4 5 6 

### Factorial of a large number

In [98]:
num = 5
num_list = []
ans_list = [1]
flag = 0
multi = 0
for i in range(num,0,-1):
    num_list.append(i)

for i in range(len(num_list)-1, -1, -1):
    # print(num_list[i])
    for j in range(len(ans_list)-1,-1,-1):
        multi = ans_list[j] * num_list[i]
        ld = int(multi%10)
        ans_list[j] = ld + flag
        flag = int(multi/10)

    if flag:
        ans_list.insert(0,flag)
        flag = 0

    # print(ans_list)  

print(ans_list)



[1, 2, 0]
