In [2]:
import numpy as np
# for vector stimulation we can use list in python

In [22]:
l = [
    [1,2,3], 
    [4,5,6],
    [7,8,9]
    ]

for i in range(0,3):
    for j in range(0,3):
        if i + j == 2:
            print(l[j][i],'',  end='')
        else:
            print('  ',end='')
    print('')

    7 
  5   
3     


In [13]:
matrix = np.arange(9)
matrix = matrix.reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### Transpose of 2d array or matrix

In [35]:
l = [
    [1,2,3], 
    [4,5,6],
    [7,8,9]
    ]

for i in range(0,3):
    for j in range(i,3):
        l[i][j], l[j][i] = l[j][i], l[i][j]

for i in range(0,3):
    for j in range(0,3):
        print(l[i][j],'',  end='')

    print('')

1 4 7 
2 5 8 
3 6 9 
