In [47]:
import numpy as np
nums = np.arange(1,10).reshape(3,3)
print(nums)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Rotating 2D Arrays

In [62]:
nums = [[5,1,9,11],[2,4,8,10],[13,3,6,7],[15,14,12,16]]

for i in range(0,len(nums)):
    for j in range(0,i+1):
        # print(nums[i][j])
        nums[i][j], nums[j][i] = nums[j][i], nums[i][j]
        
        for i in range(0,len(nums)):
            for j in range(0,len(nums[0])):
                print(nums[i][j], end=' ')
            print('')
        print('')

i, j, k = 0, len(nums[0]) - 1, 0
print('='*50)

for rows in nums:
    print(rows)
    print('-'*100)

for rows in nums:
    rows.reverse()
    

# while (i <= j):
#     nums[k][i], nums[k][j] = nums[k][j], nums[k][i]
#     k += 1
#     if k > len(nums) - 1:
#         k = 0
#         i += 1
#         j -= 1
    
#     for a in range(0,len(nums)):
#             for b in range(0,len(nums[0])):
#                 print(nums[a][b], end=' ')
#             print('')
#     print('')
    

print(nums)

5 1 9 11 
2 4 8 10 
13 3 6 7 
15 14 12 16 

5 2 9 11 
1 4 8 10 
13 3 6 7 
15 14 12 16 

5 2 9 11 
1 4 8 14 
13 3 6 7 
15 10 12 16 

5 2 13 11 
1 4 8 14 
9 3 6 7 
15 10 12 16 

5 2 13 11 
1 4 8 10 
9 3 6 7 
15 14 12 16 

5 2 13 11 
1 4 8 10 
9 3 6 12 
15 14 7 16 

5 2 13 15 
1 4 8 10 
9 3 6 12 
11 14 7 16 

5 2 13 15 
1 4 8 14 
9 3 6 12 
11 10 7 16 

5 2 13 15 
1 4 8 14 
9 3 6 7 
11 10 12 16 

5 2 13 15 
1 4 8 14 
9 3 6 7 
11 10 12 16 

[5, 2, 13, 15]
----------------------------------------------------------------------------------------------------
[1, 4, 8, 14]
----------------------------------------------------------------------------------------------------
[9, 3, 6, 7]
----------------------------------------------------------------------------------------------------
[11, 10, 12, 16]
----------------------------------------------------------------------------------------------------
[[15, 13, 2, 5], [14, 8, 4, 1], [7, 6, 3, 9], [16, 12, 10, 11]]


### Maximum Sub Array, Kdane's algorithm

In [69]:
# nums = [-2,1,-3,4,-1,2,1,-5,4]
nums = [-1]

max_sum = nums[0]
temp_sum = 0
for i in range(0,len(nums)):
    for j in range(i,len(nums)):
        temp_sum += nums[j]
        print(f'{temp_sum} is temp_sum for start point at {nums[i]}')
        if temp_sum > max_sum:
            max_sum = temp_sum
            print(f'{max_sum} is max sum')
    temp_sum = 0
print( max_sum)

-1 is temp_sum for start point at -1
-1


In [80]:
# USING KDANE'S ALGORITHM
temp_sum = 0
max_sum = nums[0]
nums = [1,2,3]
for elements in nums:
            temp_sum += elements
            # print(temp_sum, 'this is temp sum', elements)
            if temp_sum < 0:
                temp_sum = 0
            elif temp_sum > max_sum:
                max_sum = temp_sum
                # print(max_sum)
print(max_sum)

6
